### ISSUE TITLE
We  need to be able to compute associated node lists for each node

### ISSUE THREAD

**Issue by timlinux** [kartoza/stream_feature_extractor#10]
# Problem

Given a point layer add node_list and node_count and populate by generating node list, count from above method
# Proposed solution

By using method to generate list of id nearby nodes, populate the list of upstream_nodes, downstream_nodes, and count them. For each attributes, we will need a specific field in the attribute table.
# Expected outcome

We will generated information so that we can build a table like in comment below https://github.com/timlinux/stream-feature-extractor/issues/10#issuecomment-41037170

**Comment by ismailsunni** [comment]
> add node_list and node_count

Does it mean, add new attribute in the attribute table?

> generating node list

Do we put the id of the node in the node list or the geoposition (longitude latitude)? *I think it should be node_id, just for confirmation

**Comment by timlinux** [comment]
Hi

Ok so what we are aiming for is our extracted nodes layer to have a table like this:

| id | node_list | node_count |
| --- | --- | --- |
| 1 | 10, 43, 21 99 | 5 |
| 2 | 12, 15 | 2 |
- node_list should contain the id's of all other nodes that occur at the same position based on snapping distance (exclusive of the current node)
- node_count should contain the len(items in node_list) plus the current node

**Comment by ismailsunni** [comment]
After discussion we agree to create a table like this:

| id | line_id | node_type | upstream_node_list | downstream_node_list | upstream_node_count | downstream_node_count |
| --- | --- | --- | --- | --- | --- | --- |
| 1 | 1 | upstream | 5, 10 , 15 | 4, 7 | 4 | 2 |
| 2 | 1 | downstream | 12, 14, 44 | 5, 9 | 3 | 3 |
- **upstream_node_list** : contains the id's of all other upstream nodes that occur at the same position based on snapping distance (exclusive of the current node)
- **downstream_node_list** : contains the id's of all other downstream nodes that occur at the same position based on snapping distance (exclusive of the current node)
- **upstream_node_count** : contains the len(items in upstream_node_list) plus the current node if it's a upstream node
- **downstream_node_count** : contains the len(items in downstream_node_list) plus the current node if it's a downstream node
