### ISSUE TITLE
We need to be able to compute upstream and downstream node counts

### ISSUE THREAD

**Issue by timlinux** [kartoza/stream_feature_extractor#11]
# Problem

Given a line layer add columns 'upstream', 'upstream_count' and 'downstream', 'downstream_count'
# Proposed solution
# Expected outcome
# Notes

We don't need this ticket since it is covered in #10

**Comment by ismailsunni** [comment]
Does it only add columns?
And what will be the content of the columns?
And is it true that this ticket for line layer? I think it should be a point layer (the layer that has extracted nodes)
