### ISSUE TITLE
We need to be able to identify self-intersections

### ISSUE THREAD

**Issue by timlinux** [kartoza/stream_feature_extractor#17]
# Problem

If a river layer's segments have self intersections, there should be a mechanism to identify all of these segments by extracting them to a new line layer.
# Proposed solution
- [ ] @ismailsunni write a feature iterator that will test each line segment for the presence of self intersections (check the QGIS API - we already have logic for this).
- [ ] @ismailsunni for each identified segment write it to a new (memory layer)
# Expected outcome
- User should be able to extract all segments that have self intersections to a new layer.
- There is no expectation that we fix these issues (user will probably want to manually inspect and resolve).

**Comment by ismailsunni** [comment]
I think self intersection is for line, not for node. So, where do we put mark (or attribute) if the result is vector point layer? Same apply for #18

**Comment by timlinux** [comment]
@ismailsunni I updated the original issue description to make the requirements clearer. Please let me know if you need further info.

**Comment by ismailsunni** [comment]
`segments` is a line between a vertex right? 
If so, for this ticket, for each self intersection line, there will be two segments.
