### ISSUE TITLE
Create a Report that Explains The Result

### ISSUE THREAD

**Issue by ismailsunni** [kartoza/stream_feature_extractor#28]
## Problem

In Current situation, the result from the client's data set is slightly different with the result from the plugin. We need to explain why this result happened. 
## Proposed Solution

Write a small report that explains why this thing happened. For example:
1. Test dataset incorrectly identifies this as a sink but it does not match criteria
2. There were various other errors in their data, e.g. overlapping lines running in opposite directions
## Expected Result

A small report that explain the result

**Comment by ismailsunni** [comment]
The report is here : https://docs.google.com/document/d/1EKcaHjYoUBWl4GhdBcET5oPY-uh4GlfA-lehQezS3fU/edit?usp=sharing

**Comment by timlinux** [comment]
Thank you very much @ismailsunni - I have added it in this dir: https://github.com/timlinux/stream-feature-extractor/tree/develop/test/test_data/dgn
