### ISSUE TITLE
Help translation script does not work

### ISSUE THREAD

**Issue by ismailsunni** [kartoza/stream_feature_extractor#40]
## Problem

Currently, the script for translating the help is not working. It generates untranslated help.
## Proposed Solution
- Make the script works
- Add it to Make deploy
- Make sure help points to the correct localisation
## Expected Result

Help should be shown in localized mode

**Comment by timlinux** [comment]
Hi

Can you confirm this is against my most recent commits? 

Tim

**Comment by ismailsunni** [comment]
Yes, I tried it with your 04302f5
