### ISSUE TITLE
some river sections not analysed

### ISSUE THREAD

**Issue by gubuntu** [kartoza/stream_feature_extractor#51]
note the two graphs with no feature outputs
![screenshot from 2016-11-24 07-00-38](https://cloud.githubusercontent.com/assets/496911/20587185/e56a06b0-b213-11e6-9a5f-20b0836a97c7.png)

**Comment by ismailsunni** [comment]
Do you have any data test for this @gubuntu ?

**Comment by gubuntu** [comment]
[rivers.zip](https://github.com/kartoza/stream_feature_extractor/files/610557/rivers.zip)

**Comment by timlinux** [comment]
Works fine now on discrete river sections

![image](https://user-images.githubusercontent.com/178003/140920897-2382182b-f66d-48fb-be2e-f00471b79ac9.png)
