### ISSUE TITLE
incorrect flow direction

### ISSUE THREAD

**Issue by gubuntu** [kartoza/stream_feature_extractor#52]
note wells and sinks at the wrong ends of the graph
![screenshot from 2016-11-24 07-00-38](https://cloud.githubusercontent.com/assets/496911/20587198/10d1d1f2-b214-11e6-95b3-b33f2c0b45ee.png)

**Comment by timlinux** [comment]
If your line directions are flipped this will happen

![image](https://user-images.githubusercontent.com/178003/140922882-9a620223-1989-46f7-acf8-31b551fef2ba.png)


(using your other test dataset)

Labels are altitude of each point looked up from SRTM
