### ISSUE TITLE
only intersections generated on large network

### ISSUE THREAD

**Issue by gubuntu** [kartoza/stream_feature_extractor#53]
I ran the SFE on the 1:500k river network layer of southern Africa (which is a high quality connected network). It threw no errors but only output intersections
![screenshot from 2016-11-24 07-47-14](https://cloud.githubusercontent.com/assets/496911/20588008/76c0803e-b21a-11e6-8f92-b7ae55534e5e.png)

**Comment by gubuntu** [comment]
Here is one river network, a subset of the data used in the OP
[rivers.gpkg.zip](https://github.com/kartoza/stream_feature_extractor/files/610613/rivers.gpkg.zip)

**Comment by timlinux** [comment]
Running with he latest version seems to work ok:

![image](https://user-images.githubusercontent.com/178003/140920433-f1ab3f5e-2652-46b7-b1f2-7c807f4ad33c.png)
