### ISSUE TITLE
Update the test suite

### ISSUE THREAD

**Issue by vermeulendivan** [kartoza/stream_feature_extractor#74]
The test suite has been created, but will be updated to include additional comprehensive functional tests to ensure all stream features features are detected. Also, tests should also be added for issues related to data input, such as null geometries, empty features, input data which has no coordinate system set, etc.

**Comment by vermeulendivan** [comment]
Create comprehensive functional test suite to ensure all features are detected

This have been created, but will likely require improvement

**Comment by Samweli** [comment]
closed via https://github.com/kartoza/stream_feature_extractor/pull/86
