### ISSUE TITLE
Set up sentry events to work as it should

### ISSUE THREAD

**Issue by vermeulendivan** [kartoza/stream_feature_extractor#76]
Fix sentry events to correctly push errors when the user has the option enabled for the plugin.

Sentry links:
http://8a67c7961c844500a25d7dfd048c4da9:de927b27fe5342dbb358accd031661ad@sentry.kartoza.com/31
http://sentry.kartoza.com/accept/57/36a59695d32e4cd281ff74d6589289d3aa9ef6fb7a1f456590db5d77796296b7/

**Comment by vermeulendivan** [comment]
http://8a67c7961c844500a25d7dfd048c4da9:de927b27fe5342dbb358accd031661ad@sentry.kartoza.com/31
http://sentry.kartoza.com/accept/57/36a59695d32e4cd281ff74d6589289d3aa9ef6fb7a1f456590db5d77796296b7/

**Comment by Samweli** [comment]
closed via https://github.com/kartoza/stream_feature_extractor/pull/87
