### ISSUE TITLE
Test if there is any issues with the UI of the plugin

### ISSUE THREAD

**Issue by vermeulendivan** [kartoza/stream_feature_extractor#78]
Do a thorough check of the UI of the plugin. Be sure there is no errors, and if errors do occur that there is a clear instructions for the user on how to resolve the error.

**Comment by Samweli** [comment]
@vermeulendivan could you report on this? so we can close it, if you have already addressed it.

**Comment by vermeulendivan** [comment]
Testing were done on the UI: this includes the options dialog, the toolbar button, if the menu button works as it should, and if the sphinx generated html docs opens correctly when the user selects the help option. The features extracted layer adds correctly with the correct styling to qgis when ran, and the intermediate layer adds correctly when enabled. Tests were also done when QGIS is set to the german language.
