### ISSUE TITLE
OS and QGIS version testing

### ISSUE THREAD

**Issue by vermeulendivan** [kartoza/stream_feature_extractor#81]
Test the plugin on Windows, Macintosh, and Linux. The QGIS LTR, latest version (currently v3.22) and nightlies version should each be evaluated.

**Comment by Samweli** [comment]
@vermeulendivan could you report on this? so we can close it, if you have already addressed it.

**Comment by vermeulendivan** [comment]
Windows and linux has been tested. QGIS versions 3.10, 3.12, 3.14, 3.16, 3.18, 3.20 and 3.22 (latest) has been tested. Automated shell scripts has been added for local testing, and github action workflows for remote testing

**Comment by timlinux** [comment]
No macOS available - @gubuntu can you test please?

**Comment by gubuntu** [comment]
works in 3.22 on Mac, in German too.

**Comment by vermeulendivan** [comment]
Tests has been performed on Windows, Linux and MacOS.
