### ISSUE TITLE
Test gitHub actions and PR submissions

### ISSUE THREAD

**Issue by vermeulendivan** [kartoza/stream_feature_extractor#84]
Get gitHub actions set up and working correctly. Also, all PR submissions should be tested before merging. See the following for a workflow on how to accomplish this: https://github.com/north-road/qgis-processing-r/blob/master/.github/workflows/test_plugin.yaml

**Comment by Samweli** [comment]
closed via https://github.com/kartoza/stream_feature_extractor/pull/86
